import enum
from datetime import datetime

from sqlalchemy import DateTime, Enum, Index, Numeric, SmallInteger, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base
from app.models.base import TimestampMixin


class SignalType(str, enum.Enum):
    technical = "technical"
    insider = "insider"
    ai_news = "ai_news"
    options_flow = "options_flow"
    fundamental = "fundamental"
    earnings_upcoming = "earnings_upcoming"
    macro_event = "macro_event"
    cross_impact = "cross_impact"


class SignalDirection(str, enum.Enum):
    bullish = "bullish"
    bearish = "bearish"
    neutral = "neutral"


class Signal(TimestampMixin, Base):
    """
    A trading signal generated by any provider.
    Strength 1–5: 1 = weak hint, 5 = high-conviction signal.
    """
    __tablename__ = "signals"
    __table_args__ = (
        Index("ix_signals_ticker_created", "ticker", "created_at"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    ticker: Mapped[str] = mapped_column(String(20), nullable=False, index=True)
    signal_type: Mapped[SignalType] = mapped_column(
        Enum(SignalType, name="signal_type"), nullable=False
    )
    direction: Mapped[SignalDirection] = mapped_column(
        Enum(SignalDirection, name="signal_direction"), nullable=False
    )
    strength: Mapped[int] = mapped_column(SmallInteger, nullable=False)  # 1–5

    # Price levels
    entry_price: Mapped[float | None] = mapped_column(Numeric(18, 4))
    stop_loss: Mapped[float | None] = mapped_column(Numeric(18, 4))
    take_profit: Mapped[float | None] = mapped_column(Numeric(18, 4))

    # Human-readable explanation (populated by AI or rule engine)
    rationale: Mapped[str | None] = mapped_column(Text)
    # Which indicator/rule fired (e.g. "RSI_OVERSOLD,MACD_CROSS")
    indicators: Mapped[str | None] = mapped_column(String(500))

    timeframe: Mapped[str | None] = mapped_column(String(10))  # "1d", "1w", "1h"
    expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
