"""add_currency_to_trades_positions

Revision ID: 6fac7e0e8b97
Revises: 42eaf3d4d911
Create Date: 2026-04-14 22:12:10.260427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6fac7e0e8b97'
down_revision: Union[str, None] = '42eaf3d4d911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('currency', sa.String(length=10), server_default='USD', nullable=False))
    op.add_column('trades', sa.Column('currency', sa.String(length=10), server_default='USD', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'currency')
    op.drop_column('positions', 'currency')
    # ### end Alembic commands ###
