"""add_price_cache_to_watchlist_items

Revision ID: 8b6fb6bcbe86
Revises: fac24e233009
Create Date: 2026-04-15 10:19:44.185230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8b6fb6bcbe86'
down_revision: Union[str, None] = 'fac24e233009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist_items', sa.Column('last_price', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('watchlist_items', sa.Column('last_change', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('watchlist_items', sa.Column('last_change_pct', sa.Numeric(precision=8, scale=4), nullable=True))
    op.add_column('watchlist_items', sa.Column('previous_close', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('watchlist_items', sa.Column('fifty_two_week_high', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('watchlist_items', sa.Column('fifty_two_week_low', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('watchlist_items', sa.Column('price_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watchlist_items', 'price_updated_at')
    op.drop_column('watchlist_items', 'fifty_two_week_low')
    op.drop_column('watchlist_items', 'fifty_two_week_high')
    op.drop_column('watchlist_items', 'previous_close')
    op.drop_column('watchlist_items', 'last_change_pct')
    op.drop_column('watchlist_items', 'last_change')
    op.drop_column('watchlist_items', 'last_price')
    # ### end Alembic commands ###
